Third task branch
Melnikova26/test-web-bee pull request #3
Opened 2023-05-24 13:57 UTC by Melnikova26

2023-05-25 21:30 UTC, IRaccoonI requested changes

2023-05-25 21:30 UTC, IRaccoonI commented on time.html
> +        fetch('./base.html')
точка не нужна, вообще относительные пути зло, везде бы поправить
```suggestion
        fetch('/base.html')
```

2023-05-25 21:30 UTC, IRaccoonI commented on assets/js/router.js
> +    const path = location.pathname;
выглядит как ненужная переменная)

2023-05-25 21:30 UTC, IRaccoonI commented on assets/js/router.js
> +    linkElems[i].classList.add('header__nav-link_active');
не делаешь проверку на то, что этот элемент будет в списке, хотя бы так сделай
```suggestion
    linkElems[i]?.classList.add('header__nav-link_active');
```

2023-05-25 21:30 UTC, IRaccoonI commented on assets/js/router.js
> +// Time
если делаешь такой коммент, повод вынести в отдельный файл, а то получишь файл на 2к строк, что очень не желательно

2023-05-25 21:30 UTC, IRaccoonI commented on assets/js/router.js
> +    if (timer){
если тебе нужно только быть уверенным что дальше есть эта переменная лучше делать так
`if (!timer) return;`
что бы лесенок не было таких

2023-05-26 09:25 UTC, Melnikova26 commented on time.html
> +        fetch('./base.html')
поправлено

2023-05-26 09:26 UTC, Melnikova26 commented on assets/js/router.js
> +    linkElems[i].classList.add('header__nav-link_active');
поправлено

2023-05-26 09:26 UTC, Melnikova26 commented on assets/js/router.js
> +    if (timer){
поправлено

2023-05-26 10:32 UTC, merged